### ISSUE TITLE
Hyprland not found

### ISSUE THREAD

**Issue by rochecompaan** [elythh/flake#26]
Hi @elythh thank you for making your config available, it's awesome!

I used your config as a starting point for my own and I'm running into an issue where Hyprland is not found after switching to the new config. Do you install Hyprland separately with home manager or does it work for you by doing a nixos rebuild?

**Comment by elythh** [comment]
Hello ! Thanks for the kind words 
Indeed, the Hyprland installation and configuration is managed by home-managee, I do not install it using NixOS option since the config only applies for the user.
You made me realize that's probably not the smartest idea since I configure greetd to log using Hyprland..

**Comment by elythh** [comment]
You can add hyprland right here https://github.com/elythh/flake/commit/a33562f7f417c61711549919bd79e5061509965c
However it will be using the default config untill you apply the home-manager configuration

**Comment by rochecompaan** [comment]
Excellent, thank you!
